global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m
  receiver: "email"
  routes:
    - receiver: "email_1"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true

    - receiver: "email_2"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true


receivers:
  - name: 'email'
    email_configs:
    - to: email
      from: email
      smarthost: smtp.gmail.com:587
      auth_username: ''
      auth_identity: ''
      auth_password: ''
      
  - name: 'email_1'
    email_configs:
    - to: 'recipient_1@gmail.com'
      from: 'email_id_1@gmail.com'
      smarthost: smtp.gmail.com:587
      auth_username: 'email_id_1@gmail.com'
      auth_identity: 'email_id_1@gmail.com'
      auth_password: 'password_1'
  
  - name: 'email_2'
    email_configs:
    - to: 'recipient_2@gmail.com'
      from: 'email_id_2@gmail.com'
      smarthost: smtp.gmail.com:587
      auth_username: 'email_id_2@gmail.com'
      auth_identity: 'email_id_2@gmail.com'
      auth_password: 'password_2'
