version: '3.3'

networks:
  monitoring:
    driver: bridge
    

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9101:9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    restart: always 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9091:9090
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
        # - '--web.enable-lifecycle'
    ports:
      - 9095:9093
    networks:
      - monitoring
  
  consul:
    image: consul:latest
    container_name: consul
    restart: always
    ports:
      - 8500:8500
    networks:
      - monitoring 

  consul-template:
    image: consultemplate:latest
    container_name: consul-template 
    volumes:
      - ./alert.rules:/etc/prometheus/alert.rules
      - ./consul-template/alert.tpl:/etc/prometheus/alert.tpl
    #command: -consul=localhost:8500 -template="/etc/prometheus/alert.tpl:/etc/prometheus/alert.rules"
    ports:
      - 8501:8500
    restart: always
    networks:
      - monitoring

